### ISSUE TITLE
TypeError: Canvas.registerFont is not a function

### ISSUE THREAD

**Issue by dreaming-augustin** [larskarbo/napchart#48]
We cannot get an image:
http://napchart.com/api/getImage?width=600&height=600&chartid=0ttrx 

```
TypeError: Canvas.registerFont is not a function
    at module.exports (/app/server/api/getImage.js:18:10)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at next (/app/node_modules/express/lib/router/route.js:127:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)
    at next (/app/node_modules/express/lib/router/route.js:131:14)

```
For the rest, http://napchart.com/app is a very nice web site / application! Thanks! :)

**Comment by larskarbo** [comment]
Hi, thanks for the bug report!

I looked into it, and I couldn't figure excactly why it didn't work. However, I tried to upgrad `canvas` to `v2`, and it works now 🙌

**Comment by dreaming-augustin** [comment]
Thank you for the quick fix! :)
